# This workflow will do a clean installation of node dependencies, cache/restore them, build the
# source code and run tests across different versions of node
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Clean npm config
        run: npm config delete registry
      
      - name: Set npm registry to official
        run: npm config set registry https://registry.npmjs.org/
      
      - name: Install
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build --openssl-legacy-provider

      - name: GH Pages deploy
        uses: Cecilapp/GitHub-Pages-deploy@3.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # A verified email.
          email: ${{ secrets.EMAIL }}
          # Where static files are.
          build_dir: dist
          branch: gh-pages
          cname: ntpu-timetable.littlechin.tw
