name: Python CI
on:
  push:
  schedule:
    - cron: "0 0 * * 2,4,6"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: clawer/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r clawer/requirements.txt
      - name: Run Python
        run: python3 clawer/main.py
      - name: Commit
        continue-on-error: true
        run: |
          git config --global user.email "littlechintw@gmail.com"
          git config --global user.name "littlechintw"
          git commit -a -m "Upgrade data by github actions"
      - name: Push Changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
