name: Python CI Push
on: push
    
jobs:
  build:
    runs-on: ubuntu-latest			
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r clawer/requirements.txt
    - name: Run Python
      id: generator
      run: python3 clawer/main.py
    - name: Commit
      continue-on-error: true
      run: |
        git config --global user.email "littlechintw@gmail.com"
        git config --global user.name "littlechintw"
        git add -A
        git commit -m "Upgrade data by github actions"
    - name: Push Changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GIT_TOKEN }}
